$(".bar").click(function(){
    $(".side-ber").addClass("test")
    $(".side-ber-tow").addClass("test2")
})
$(".close").click(function(){
    $(".side-ber").removeClass("test")
    $(".side-ber-tow").removeClass("test2")
})
$(".home").click(function(){
    $(".drop").slideToggle()
    $(".bar2").toggleClass("cls")
})
$(".teams").click(function(){
    $(".drop2").slideToggle()
       $(".bar3").toggleClass("cls")
})
$(".Services").click(function(){
    $(".drop3").slideToggle()
       $(".bar4").toggleClass("cls")
})
$(".Shops").click(function(){
    $(".drop4").slideToggle()
       $(".bar5").toggleClass("cls")
})
$(".Pages").click(function(){
    $(".drop5").slideToggle()
       $(".bar6").toggleClass("cls")
})
$(".Blog").click(function(){
    $(".drop6").slideToggle()
       $(".bar7").toggleClass("cls")
})